added error log and exit status check

diff --git a/up b/up
--- a/up
+++ b/up
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # A script to update a linux distro based on Arch, OpenSUSE, Fedora or Debian.
-#
+# Version: 0.1
 # Copyright (C) 2024 Ronald Jørnsøn
 # 45grn6meov@runbox.email
 #
@@ -9,34 +9,48 @@
 #
 # https://www.gnu.org/licenses/gpl-3.0-standalone.html
 
-set -e
+#set -e
 
 release_file=/etc/os-release
+errorlog=/var/log/updater_errors.log
+
+check_exit_status() {
+  if [ $? -ne 0 ]; then
+    echo "An error occured. Check the $errorlog file."
+  fi
+}
 
 if grep -q "debian" $release_file ; then
   # the host is based on Debian, run the apt update command.
-  sudo apt-get update
-  sudo apt-get dist-upgrade -y
+  sudo apt-get update 2>>$errorlog
+  check_exit_status
+
+  sudo apt-get dist-upgrade -y 2>>$errorlog
+  check_exit_status
 fi
 
 if grep -q "Arch" $release_file ; then
   # the host is based on arch, run the pacman update command.
-  sudo pacman -Syu
+  sudo pacman -Syu 2>>$errorlog
+  check_exit_status
 fi
 
 if grep -q "Fedora" $release_file ; then
   # the host is based on Fedora, run the dnf upgrade command
-  sudo dnf upgrade
+  sudo dnf upgrade 2>>$errorlog
+  check_exit_status
 fi
 
 if grep -q "opensuse-tumbleweed" $release_file ; then
   # the host is based on OpenSUSE Tumbleweed, run the zypper command
-  sudo zypper dup
+  sudo zypper dup 2>>$errorlog
+  check_exit_status
 fi
 
 if grep -q "opensuse-leap" $release_file ; then
   # the host is based on OpenSUSE Leap, run the zypper command
-  sudo zypper up
+  sudo zypper up 2>>$errorlog
+  check_exit_status
 fi
 
 exit
